from database.mongodb import Database
from reviews_management.application.use_cases.create_valoration_use_cases import CreateValorationUseCase
from reviews_management.application.use_cases.delete_valoration_use_cases import DeleteValorationUseCase
from reviews_management.application.use_cases.get_valoration_use_cases import GetByUuidValorationUseCase
from reviews_management.application.use_cases.list_valorations_use_cases import ListValorationUseCase
from reviews_management.application.use_cases.update_valoration_use_cases import UpdateValorationUseCase
from reviews_management.infraestructure.controllers.create_valoration_controller import CreateValorationController
from reviews_management.infraestructure.controllers.delete_valoration_controller import DeleteValorationController
from reviews_management.infraestructure.controllers.get_valoration_controller import GetValorationController
from reviews_management.infraestructure.controllers.list_valorations_controller import ListValorationController
from reviews_management.infraestructure.repositories.valorations_mongo_repository import ValorationMongoRepository


mongoconnection = Database()

repository = ValorationMongoRepository(mongoconnection)

create_use_case = CreateValorationUseCase(repository)
list_use_case = ListValorationUseCase(repository)
update_use_case = UpdateValorationUseCase(repository)
delete_use_case = DeleteValorationUseCase(repository)
get_by_uuid_use_case = GetByUuidValorationUseCase(repository)

create_controller = CreateValorationController(create_use_case)
list_controller = ListValorationController(list_use_case)
update_controller = CreateValorationController(update_use_case)
delete_controller = DeleteValorationController(delete_use_case)
get_by_uuid_controller = GetValorationController(get_by_uuid_use_case)